[workspace]
authors = ["Mayur <mayurks@uia.no>"]
channels = ["conda-forge"]
name = "PneumoniaMNIST_Experiments"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12"

[dependencies]
python = ">=3.13.5,<3.14"
cuda = ">=12.9.1,<13"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"
numpy = ">=2.3.1,<3"

[pypi-dependencies]
medmnist = ">=3.0.2, <4"
# pysparsecoalescedtsetlinmachinecuda = { git = "https://github.com/Mayur1009/PySparseCoalescedTsetlinMachineCUDA", branch = "dev" }
pysparsecoalescedtsetlinmachinecuda = { git = "https://github.com/cair/PySparseCoalescedTsetlinMachineCUDA" }
microsoft-python-type-stubs = { git = "https://github.com/microsoft/python-type-stubs.git" }
pycuda = "*"
